export const providerIconMap: Map<string, string> = new Map([
  ["bank_of_america", "/icons/bank_of_america.svg"],
  ["binance", "/icons/binance.svg"],
  ["bnp_paribas", "/icons/bnp_paribas.svg"],
  ["boursorama", "/icons/boursorama.svg"],
  ["citibank", "/icons/citibank.png"],
  ["coinbase", "/icons/coinbase.svg"],
  ["credit_agricole", "/icons/credit_agricole.svg"],
  ["jp_morgan_chase", "/icons/jp_morgan_chase.webp"],
  ["kakao_bank", "/icons/kakao_bank.jpg"],
  ["orange_bank", "/icons/orange_bank.png"],
  ["ledger", "/icons/ledger.svg"],
  ["shinhan_bank", "/icons/shinhan_bank.svg"],
  ["societe_generale", "/icons/societe_generale.svg"],
  ["wells_fargo", "/icons/wells_fargo.png"],
])
